### ISSUE TITLE
Squiggly <<~ HEREDOC requires Ruby 2.3+ 

### ISSUE THREAD

**Issue by specious** [daveyarwood/rubylisp#1]
The squiggly heredoc was [introduced in Ruby 2.3](https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc), so `rbl` is breaking on older Ruby interpreter.

```
$ bin/rbl
bin/rbl:7: syntax error, unexpected <<
USAGE = <<~HEREDOC
          ^
bin/rbl:8: syntax error, unexpected ':', expecting end-of-input

$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```

Gemfile should require `ruby '>=2.3'` or perhaps squiggly heredoc should be sacrificed.

**Comment by daveyarwood** [comment]
I think I'd like to opt for requiring Ruby >= 2.3, as I'm not sure what else in the code might require at least 2.3.

If you wouldn't mind making a PR, I'd be happy to merge it!
