### ISSUE TITLE
Readline crashes with invalid index error

### ISSUE THREAD

**Issue by specious** [daveyarwood/rubylisp#3]
Readline crashes on anything other than empty input.

```
$  bin/rbl
user>

user> (+ 1 1)
/Users/specious/c3/rubylisp/lib/rubylisp/rbl_readline.rb:20:in `[]': invalid index (IndexError)
        from /Users/specious/c3/rubylisp/lib/rubylisp/rbl_readline.rb:20:in `_readline'
        from /Users/specious/c3/rubylisp/lib/rubylisp/repl.rb:12:in `start'
        from bin/rbl:17:in `<main>'
```

Latest 1c9ff77, same result with Ruby 2.3.0 or 2.4.1.

**Comment by daveyarwood** [comment]
Nice catch!

Fixed by https://github.com/daveyarwood/rubylisp/commit/f59b825a0d7e268d3353603266079b32fc2a53d9. I also pushed a new version (0.0.7) to RubyGems with this fix.
